-- Generated DDL with auto-increment identities (Aurora PostgreSQL)
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- TABLE: silver_taxonomies
CREATE TABLE IF NOT EXISTS silver_taxonomies (
    taxonomy_id BIGINT,
    customer_id VARCHAR(255),
    name VARCHAR(200),
    type VARCHAR(10),
    status VARCHAR(10),
    created_at TIMESTAMPTZ,
    last_updated_at TIMESTAMPTZ,
    load_id BIGINT,
    taxonomy_description TEXT,
    PRIMARY KEY (taxonomy_id),
    UNIQUE(taxonomy_id,customer_id),
    CHECK (status IN ('active','inactive')),
    CHECK (type IN ('master','customer'))
);

-- TABLE: bronze_load_details
CREATE TABLE IF NOT EXISTS bronze_load_details (
    load_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    customer_id VARCHAR(255),
    taxonomy_id BIGINT,
    load_details JSONB,
    load_date TIMESTAMPTZ,
    load_start TIMESTAMPTZ,
    load_end TIMESTAMPTZ,
    load_status VARCHAR(10),
    load_active_flag BOOLEAN,
    load_type VARCHAR(10),
    taxonomy_type  VARCHAR(10),
    PRIMARY KEY (load_id),
    FOREIGN KEY (customer_id, taxonomy_id) REFERENCES silver_taxonomies(customer_id, taxonomy_id),
    CHECK (load_type IN ('new','updated')),
    CHECK (taxonomy_type IN ('master','customer')),
    CHECK (load_status IN ('in progress','completed','failed'))
);

-- TABLE: bronze_taxonomies
CREATE TABLE IF NOT EXISTS bronze_taxonomies (
    row_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    load_id BIGINT,
    customer_id VARCHAR(255),
    taxonomy_id BIGINT,
    row_json JSONB,
    row_load_status VARCHAR(10),
    row_active_flag BOOLEAN,
    PRIMARY KEY (row_id),
    FOREIGN KEY (load_id) REFERENCES bronze_load_details(load_id),
    FOREIGN KEY (customer_id, taxonomy_id) REFERENCES silver_taxonomies(customer_id, taxonomy_id),
    CHECK (row_load_status IN ('in progress','completed','failed'))
);

-- TABLE: silver_taxonomies_log
CREATE TABLE IF NOT EXISTS silver_taxonomies_log (
    taxonomy_id BIGINT,
    old_row JSONB,
    new_row JSONB,
    operation_type VARCHAR(10),
    operation_date TIMESTAMPTZ,
    "user" VARCHAR(255),
    FOREIGN KEY (taxonomy_id) REFERENCES silver_taxonomies(taxonomy_id),
     CHECK (operation_type IN ('insert','update','delete'))
);

-- TABLE: silver_taxonomies_nodes_types
CREATE TABLE IF NOT EXISTS silver_taxonomies_nodes_types (
    node_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(200),
    status VARCHAR(10),
    created_at TIMESTAMPTZ,
    last_updated_at TIMESTAMPTZ,
    load_id BIGINT,
    PRIMARY KEY(node_type_id),
    FOREIGN KEY (load_id) REFERENCES bronze_load_details(load_id),
    CHECK (status IN ('active','inactive'))
);

-- TABLE: silver_taxonomies_nodes
CREATE TABLE IF NOT EXISTS silver_taxonomies_nodes (
    node_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    node_type_id BIGINT,
    taxonomy_id BIGINT,
    parent_node_id BIGINT,
    value VARCHAR(1000),
    profession VARCHAR(1000),
    level INTEGER,
    status VARCHAR(10),
    created_at TIMESTAMPTZ,
    last_updated_at TIMESTAMPTZ,
    load_id BIGINT,
    row_id BIGINT,
    PRIMARY KEY (node_id),
    CHECK (status IN ('active','inactive')),
    CHECK (level >= 0),
  FOREIGN KEY (node_type_id) REFERENCES silver_taxonomies_nodes_types(node_type_id),
    FOREIGN KEY (taxonomy_id) REFERENCES silver_taxonomies(taxonomy_id),
    FOREIGN KEY (parent_node_id) REFERENCES silver_taxonomies_nodes(node_id),
    FOREIGN KEY (load_id) REFERENCES bronze_load_details(load_id),
    FOREIGN KEY (row_id) REFERENCES bronze_taxonomies(row_id)
);

-- TABLE: silver_taxonomies_nodes_log

CREATE TABLE IF NOT EXISTS silver_taxonomies_nodes_log (
    node_id BIGINT,
    old_row JSONB,
    new_row JSONB,
    operation_type VARCHAR(10),
    operation_date TIMESTAMPTZ,
    "user" VARCHAR(255),
    FOREIGN KEY (node_id) REFERENCES silver_taxonomies_nodes(node_id),
     CHECK (operation_type IN ('insert','update','delete'))
);

-- TABLE: silver_taxonomies_nodes_log

CREATE TABLE IF NOT EXISTS silver_taxonomies_nodes_types_log (
    node_type_id BIGINT,
    old_row JSONB,
    new_row JSONB,
    operation_type VARCHAR(10),
    operation_date TIMESTAMPTZ,
    "user" VARCHAR(255),
    FOREIGN KEY (node_type_id) REFERENCES silver_taxonomies_nodes_types(node_type_id),
     CHECK (operation_type IN ('insert','update','delete'))
);

-- TABLE: silver_mapping_taxonomies_rules
CREATE TABLE IF NOT EXISTS silver_mapping_taxonomies_rules (
    mapping_rule_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(1000),
    enabled BOOLEAN,
    pattern VARCHAR(2000),
    attributes VARCHAR(500),
    flags VARCHAR(500),
    action VARCHAR(500),
    command VARCHAR(100),
    AI_mapping_flag BOOLEAN,
    Human_mapping_flag BOOLEAN,
    created_at TIMESTAMPTZ,
    last_updated_at TIMESTAMPTZ,
    PRIMARY KEY (mapping_rule_id),
    UNIQUE(name)
);


-- TABLE: silver_mapping_taxonomies_rules_log
CREATE TABLE IF NOT EXISTS silver_mapping_taxonomies_rules_log (
    mapping_rule_id BIGINT,
    old_row JSONB,
    new_row JSONB,
    operation_type VARCHAR(10),
    operation_date TIMESTAMPTZ,
    "user" VARCHAR(255),
    FOREIGN KEY (mapping_rule_id) REFERENCES silver_mapping_taxonomies_rules(mapping_rule_id),
    CHECK (operation_type IN ('insert','update','delete'))
);

-- TABLE: silver_mapping_taxonomies_rules_assigment
CREATE TABLE IF NOT EXISTS silver_mapping_taxonomies_rules_assigment (
    mapping_rule_assigment_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    mapping_rule_id BIGINT,
    master_node_type_id BIGINT,
    child_node_type_id BIGINT,
    priority INTEGER,
    enabled BOOLEAN,
    created_at TIMESTAMPTZ,
    last_updated_at TIMESTAMPTZ,
    PRIMARY KEY (mapping_rule_assigment_id),
    CHECK (priority >= 1),
    FOREIGN KEY (mapping_rule_id) REFERENCES silver_mapping_taxonomies_rules(mapping_rule_id),
    FOREIGN KEY (master_node_type_id) REFERENCES silver_taxonomies_nodes_types(node_type_id),
    FOREIGN KEY (child_node_type_id) REFERENCES silver_taxonomies_nodes_types(node_type_id)
);

-- TABLE: silver_mapping_taxonomies_rules_log
CREATE TABLE IF NOT EXISTS silver_mapping_rules_assigment_log (
    mapping_rule_assigment_id BIGINT,
    old_row JSONB,
    new_row JSONB,
    operation_type VARCHAR(10),
    operation_date TIMESTAMPTZ,
    "user" VARCHAR(255),
    FOREIGN KEY (mapping_rule_assigment_id) REFERENCES silver_mapping_taxonomies_rules_assigment(mapping_rule_assigment_id),
    CHECK (operation_type IN ('insert','update','delete'))
);

-- TABLE: silver_mapping_taxonomies
CREATE TABLE IF NOT EXISTS silver_mapping_taxonomies (
    mapping_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    mapping_rule_id BIGINT,
    master_node_id BIGINT,
    child_node_id BIGINT,
    status VARCHAR(10),
    "user" VARCHAR(255) ,
    created_at TIMESTAMPTZ,
    last_updated_at TIMESTAMPTZ,
    PRIMARY KEY (mapping_id),
    CHECK (status IN ('active','inactive')),
    FOREIGN KEY (mapping_rule_id) REFERENCES silver_mapping_taxonomies_rules(mapping_rule_id),
    FOREIGN KEY (master_node_id) REFERENCES silver_taxonomies_nodes(node_id),
    FOREIGN KEY (child_node_id) REFERENCES silver_taxonomies_nodes(node_id)
);

-- TABLE: gold_mapping_taxonomies
CREATE TABLE IF NOT EXISTS gold_mapping_taxonomies (
    mapping_id BIGINT,
    master_node_id BIGINT,
    child_node_id BIGINT,
    created_at TIMESTAMPTZ,
    last_updated_at TIMESTAMPTZ,
    UNIQUE(mapping_id),
    FOREIGN KEY (mapping_id) REFERENCES silver_mapping_taxonomies(mapping_id),
    FOREIGN KEY (master_node_id) REFERENCES silver_taxonomies_nodes(node_id),
    FOREIGN KEY (child_node_id) REFERENCES silver_taxonomies_nodes(node_id)
);

-- TABLE: gold_mapping_taxonomies_log
CREATE TABLE IF NOT EXISTS gold_mapping_taxonomies_log (
    mapping_id BIGINT,
    old_row JSONB,
    new_row JSONB,
    operation_type VARCHAR(10),
    operation_date TIMESTAMPTZ,
    "user" VARCHAR(255),
    FOREIGN KEY (mapping_id) REFERENCES gold_mapping_taxonomies(mapping_id),
    CHECK (operation_type IN ('insert','update','delete'))
);

-- TABLE: silver_taxonomies_attribute_types
CREATE TABLE IF NOT EXISTS silver_taxonomies_attribute_types (
    attribute_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(200),
    status VARCHAR(10),
    created_at TIMESTAMPTZ,
    last_updated_at TIMESTAMPTZ,
    load_id BIGINT,
    PRIMARY KEY (attribute_type_id),
    FOREIGN KEY (load_id) REFERENCES bronze_load_details(load_id),
    CHECK (status IN ('active','inactive'))
);


-- TABLE: silver_taxonomies_nodes_attributes
CREATE TABLE IF NOT EXISTS silver_taxonomies_nodes_attributes (
    node_attribute_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    attribute_type_id BIGINT,
    node_id BIGINT,
    value VARCHAR(1000),
    status VARCHAR(10),
    created_at TIMESTAMPTZ,
    last_updated_at TIMESTAMPTZ,
    load_id BIGINT,
    row_id BIGINT,
    PRIMARY KEY (node_attribute_type_id),
    FOREIGN KEY (attribute_type_id) REFERENCES silver_taxonomies_attribute_types(attribute_type_id),
    FOREIGN KEY (node_id) REFERENCES silver_taxonomies_nodes(node_id),
    FOREIGN KEY (load_id) REFERENCES bronze_load_details(load_id),
    FOREIGN KEY (row_id) REFERENCES bronze_taxonomies(row_id),
    CHECK (status IN ('active','inactive'))
);

-- TABLE: silver_taxonomies_nodes_attributes_log

CREATE TABLE IF NOT EXISTS silver_taxonomies_nodes_attributes_log (
    node_attribute_type_id BIGINT,
    old_row JSONB,
    new_row JSONB,
    operation_type VARCHAR(10),
    operation_date TIMESTAMPTZ,
    "user" VARCHAR(255),
    FOREIGN KEY (node_attribute_type_id) REFERENCES silver_taxonomies_nodes_attributes(node_attribute_type_id),
    CHECK (operation_type IN ('insert','update','delete'))
);

-- TABLE: silver_taxonomies_attribute_types_log

CREATE TABLE IF NOT EXISTS silver_taxonomies_attribute_types_log (
    attribute_type_id BIGINT,
    old_row JSONB,
    new_row JSONB,
    operation_type VARCHAR(10),
    operation_date TIMESTAMPTZ,
    "user" VARCHAR(255),
    FOREIGN KEY (attribute_type_id) REFERENCES silver_taxonomies_attribute_types(attribute_type_id),
    CHECK (operation_type IN ('insert','update','delete'))
);

-- TABLE: silver_taxonomies_versions
CREATE TABLE IF NOT EXISTS silver_taxonomies_versions (
    taxonomy_version_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    taxonomy_id BIGINT,
    taxonomy_version_number INTEGER,
    change_type VARCHAR(255),
    affected_nodes JSONB,
    affected_attributes JSONB,
    remapping_flag BOOLEAN,
    remapping_reason TEXT,
    total_mappings_processed INTEGER,
    total_mappings_changed INTEGER,
    total_mappings_unchanged INTEGER,
    total_mappings_failed INTEGER,
    total_mappings_new INTEGER,
    remapping_proces_status VARCHAR(10),
    version_notes TEXT,
    version_from_date TIMESTAMPTZ,
    version_to_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ,
    last_updated_at TIMESTAMPTZ,
    load_id BIGINT,
    PRIMARY KEY (taxonomy_version_id),
    FOREIGN KEY (taxonomy_id) REFERENCES silver_taxonomies(taxonomy_id),
    FOREIGN KEY (load_id) REFERENCES bronze_load_details(load_id)
);

CREATE TABLE IF NOT EXISTS silver_taxonomies_versions_log (
    taxonomy_version_id BIGINT,
    old_row JSONB,
    new_row JSONB,
    operation_type VARCHAR(10),
    operation_date TIMESTAMPTZ,
    "user" VARCHAR(255),
    FOREIGN KEY (taxonomy_version_id) REFERENCES silver_taxonomies_versions(taxonomy_version_id),
    CHECK (operation_type IN ('insert','update','delete'))
);

-- TABLE: silver_mapping_taxonomies_versions
CREATE TABLE IF NOT EXISTS silver_mapping_taxonomies_versions (
    mapping_version_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    mapping_id BIGINT,
    mapping_version_number INTEGER,
    version_from_date TIMESTAMPTZ,
    version_to_date TIMESTAMPTZ,
    superseded_by_mapping_id BIGINT,
    superseded_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ,
    last_updated_at TIMESTAMPTZ,
    PRIMARY KEY (mapping_version_id),
    FOREIGN KEY (mapping_id) REFERENCES silver_mapping_taxonomies(mapping_id),
    FOREIGN KEY (superseded_by_mapping_id) REFERENCES silver_mapping_taxonomies(mapping_id)
);

CREATE TABLE IF NOT EXISTS silver_mapping_taxonomies_versions_log (
    mapping_version_id BIGINT,
    old_row JSONB,
    new_row JSONB,
    operation_type VARCHAR(10),
    operation_date TIMESTAMPTZ,
    "user" VARCHAR(255),
    FOREIGN KEY (mapping_version_id) REFERENCES silver_mapping_taxonomies_versions(mapping_version_id),
    CHECK (operation_type IN ('insert','update','delete'))
);

-- Indexes
CREATE INDEX IF NOT EXISTS bronze_taxonomies_load_id_idx ON bronze_taxonomies (load_id);
CREATE INDEX IF NOT EXISTS bronze_taxonomies_taxonomy_id_idx ON bronze_taxonomies (taxonomy_id);
CREATE INDEX IF NOT EXISTS bronze_taxonomies_row_json_gin ON bronze_taxonomies USING GIN (row_json jsonb_path_ops);
CREATE INDEX IF NOT EXISTS bronze_taxonomies_row_load_status_lower_idx ON bronze_taxonomies (lower(row_load_status));
CREATE INDEX IF NOT EXISTS bronze_taxonomies_row_load_status_trgm ON bronze_taxonomies USING GIN (row_load_status gin_trgm_ops);
CREATE INDEX IF NOT EXISTS bronze_taxonomies_row_active_flag_true_idx ON bronze_taxonomies (row_active_flag);
CREATE INDEX IF NOT EXISTS bronze_taxonomies_customer_id_idx ON bronze_taxonomies (customer_id);
CREATE INDEX IF NOT EXISTS bronze_taxonomies_cust_tax_idx ON bronze_taxonomies (customer_id, taxonomy_id);
CREATE INDEX IF NOT EXISTS bronze_load_details_taxonomy_id_idx ON bronze_load_details (taxonomy_id);
CREATE INDEX IF NOT EXISTS bronze_load_details_load_id_lower_idx ON bronze_load_details (load_id);
CREATE INDEX IF NOT EXISTS bronze_load_details_load_end_lower_idx ON bronze_load_details USING BRIN (load_end);
CREATE INDEX IF NOT EXISTS bronze_load_details_load_end_lower_idx ON bronze_load_details USING BRIN (load_start);
CREATE INDEX IF NOT EXISTS bronze_load_details_load_status_lower_idx ON bronze_load_details (lower(load_status));
CREATE INDEX IF NOT EXISTS bronze_load_details_load_status_trgm ON bronze_load_details USING GIN (load_status gin_trgm_ops);
CREATE INDEX IF NOT EXISTS bronze_load_details_load_active_flag_true_idx ON bronze_load_details (load_active_flag);
CREATE INDEX IF NOT EXISTS bronze_load_details_load_date_brin ON bronze_load_details USING BRIN (load_date);
CREATE INDEX IF NOT EXISTS bronze_load_details_customer_id_idx ON bronze_load_details (customer_id);
CREATE INDEX IF NOT EXISTS bronze_load_details_cust_tax_idx ON bronze_load_details (customer_id, taxonomy_id);
CREATE INDEX IF NOT EXISTS silver_taxonomies_load_id_idx ON silver_taxonomies (load_id);
CREATE INDEX IF NOT EXISTS silver_taxonomies_name_lower_idx ON silver_taxonomies (lower(name));
CREATE INDEX IF NOT EXISTS silver_taxonomies_name_trgm ON silver_taxonomies USING GIN (name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_status_lower_idx ON silver_taxonomies (lower(status));
CREATE INDEX IF NOT EXISTS silver_taxonomies_status_trgm ON silver_taxonomies USING GIN (status gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_created_at_brin ON silver_taxonomies USING BRIN (created_at);
CREATE INDEX IF NOT EXISTS silver_taxonomies_last_updated_at_brin ON silver_taxonomies USING BRIN (last_updated_at);
CREATE INDEX IF NOT EXISTS silver_taxonomies_customer_id_idx ON silver_taxonomies (customer_id);
CREATE INDEX IF NOT EXISTS silver_taxonomies_cust_tax_idx ON silver_taxonomies (customer_id, taxonomy_id);
CREATE INDEX IF NOT EXISTS silver_taxonomies_desc_trgm_idx ON silver_taxonomies USING GIN (taxonomy_description gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_log_old_row_gin ON silver_taxonomies_log USING GIN (old_row jsonb_path_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_log_new_row_gin ON silver_taxonomies_log USING GIN (new_row jsonb_path_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_log_update_lower_idx ON silver_taxonomies_log (lower(operation_type));
CREATE INDEX IF NOT EXISTS silver_taxonomies_log_update_trgm ON silver_taxonomies_log USING GIN (operation_type gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_log_user_lower_idx ON silver_taxonomies_log (lower("user"));
CREATE INDEX IF NOT EXISTS silver_taxonomies_log_user_trgm ON silver_taxonomies_log USING GIN ("user" gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_log_operation_date_brin ON silver_taxonomies_log USING BRIN (operation_date);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_node_type_id_idx ON silver_taxonomies_nodes (node_type_id);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_taxonomy_id_idx ON silver_taxonomies_nodes (taxonomy_id);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_parent_node_id_idx ON silver_taxonomies_nodes (parent_node_id);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_load_id_idx ON silver_taxonomies_nodes (load_id);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_row_id_idx ON silver_taxonomies_nodes (row_id);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_value_lower_idx ON silver_taxonomies_nodes (lower(value));
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_value_trgm ON silver_taxonomies_nodes USING GIN (value gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_profession_lower_idx ON silver_taxonomies_nodes (lower(profession));
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_profession_trgm ON silver_taxonomies_nodes USING GIN (profession gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_status_lower_idx ON silver_taxonomies_nodes (lower(status));
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_status_trgm ON silver_taxonomies_nodes USING GIN (status gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_created_at_brin ON silver_taxonomies_nodes USING BRIN (created_at);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_last_updated_at_brin ON silver_taxonomies_nodes USING BRIN (last_updated_at);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_tax_type_idx ON silver_taxonomies_nodes (taxonomy_id, node_type_id);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_parent_idx ON silver_taxonomies_nodes (parent_node_id);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_level_idx ON silver_taxonomies_nodes (level);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_log_old_row_gin ON silver_taxonomies_nodes_log USING GIN (old_row jsonb_path_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_log_new_row_gin ON silver_taxonomies_nodes_log USING GIN (new_row jsonb_path_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_log_update_lower_idx ON silver_taxonomies_nodes_log (lower(operation_type));
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_log_update_trgm ON silver_taxonomies_nodes_log USING GIN (operation_type gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_log_user_lower_idx ON silver_taxonomies_nodes_log (lower("user"));
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_log_user_trgm ON silver_taxonomies_nodes_log USING GIN ("user" gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_log_operation_date_brin ON silver_taxonomies_nodes_log USING BRIN (operation_date);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_types_node_type_id_idx ON silver_taxonomies_nodes_types (node_type_id);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_types_name_lower_idx ON silver_taxonomies_nodes_types (lower(name));
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_types_name_trgm ON silver_taxonomies_nodes_types USING GIN (name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_types_status_lower_idx ON silver_taxonomies_nodes_types (lower(status));
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_types_status_trgm ON silver_taxonomies_nodes_types USING GIN (status gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_types_created_at_brin ON silver_taxonomies_nodes_types USING BRIN (created_at);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_types_last_updated_at_brin ON silver_taxonomies_nodes_types USING BRIN (last_updated_at);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_types_log_node_type_id_idx ON silver_taxonomies_nodes_types_log (node_type_id);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_types_log_old_row_gin ON silver_taxonomies_nodes_types_log USING GIN (old_row jsonb_path_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_types_log_new_row_gin ON silver_taxonomies_nodes_types_log USING GIN (new_row jsonb_path_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_types_log_update_lower_idx ON silver_taxonomies_nodes_types_log (lower(operation_type));
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_types_log_update_trgm ON silver_taxonomies_nodes_types_log USING GIN (operation_type gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_types_log_user_lower_idx ON silver_taxonomies_nodes_types_log (lower("user"));
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_types_log_user_trgm ON silver_taxonomies_nodes_types_log USING GIN ("user" gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_types_log_operation_date_brin ON silver_taxonomies_nodes_types_log USING BRIN (operation_date);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_rules_name_lower_idx ON silver_mapping_taxonomies_rules (lower(name));
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_rules_name_trgm ON silver_mapping_taxonomies_rules USING GIN (name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_rules_enabled_true_idx ON silver_mapping_taxonomies_rules (enabled);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_rules_pattern_lower_idx ON silver_mapping_taxonomies_rules (lower(pattern));
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_rules_pattern_trgm ON silver_mapping_taxonomies_rules USING GIN (pattern gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_rules_attributes_gin ON silver_mapping_taxonomies_rules USING GIN (attributes gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_rules_flags_lower_idx ON silver_mapping_taxonomies_rules (lower(flags));
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_rules_flags_trgm ON silver_mapping_taxonomies_rules USING GIN (flags gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_rules_action_lower_idx ON silver_mapping_taxonomies_rules (lower(action));
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_rules_action_trgm ON silver_mapping_taxonomies_rules USING GIN (action gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_rules_AI_mapping_flag_true_idx ON silver_mapping_taxonomies_rules (AI_mapping_flag);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_rules_Human_mapping_flag_true_idx ON silver_mapping_taxonomies_rules (Human_mapping_flag);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_rules_created_at_brin ON silver_mapping_taxonomies_rules USING BRIN (created_at);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_rules_last_updated_at_brin ON silver_mapping_taxonomies_rules USING BRIN (last_updated_at);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_rules_log_old_row_gin ON silver_mapping_taxonomies_rules_log USING GIN (old_row jsonb_path_ops);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_rules_log_new_row_gin ON silver_mapping_taxonomies_rules_log USING GIN (new_row jsonb_path_ops);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_rules_log_update_lower_idx ON silver_mapping_taxonomies_rules_log (lower(operation_type));
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_rules_log_update_trgm ON silver_mapping_taxonomies_rules_log USING GIN (operation_type gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_rules_log_user_lower_idx ON silver_mapping_taxonomies_rules_log (lower("user"));
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_rules_log_user_trgm ON silver_mapping_taxonomies_rules_log USING GIN ("user" gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_rules_log_operation_date_brin ON silver_mapping_taxonomies_rules_log USING BRIN (operation_date);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_rules_assigment_mapping_rule_assigment_id_idx ON silver_mapping_taxonomies_rules_assigment (mapping_rule_assigment_id);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_rules_assigment_master_node_type_id_idx ON silver_mapping_taxonomies_rules_assigment (master_node_type_id);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_rules_assigment_child_node_type_id_idx ON silver_mapping_taxonomies_rules_assigment (child_node_type_id);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_rules_assigment_enabled_true_idx ON silver_mapping_taxonomies_rules_assigment (enabled);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_rules_assigment_created_at_brin ON silver_mapping_taxonomies_rules_assigment USING BRIN (created_at);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_rules_assigment_last_updated_at_brin ON silver_mapping_taxonomies_rules_assigment USING BRIN (last_updated_at);
CREATE INDEX IF NOT EXISTS silver_mapping_rules_assigment_log_mapping_rule_assigment_id_idx ON silver_mapping_rules_assigment_log (mapping_rule_assigment_id);
CREATE INDEX IF NOT EXISTS silver_mapping_rules_assigment_log_old_row_gin ON silver_mapping_rules_assigment_log USING GIN (old_row jsonb_path_ops);
CREATE INDEX IF NOT EXISTS silver_mapping_rules_assigment_log_new_row_gin ON silver_mapping_rules_assigment_log USING GIN (new_row jsonb_path_ops);
CREATE INDEX IF NOT EXISTS silver_mapping_rules_assigment_log_update_lower_idx ON silver_mapping_rules_assigment_log (lower(operation_type));
CREATE INDEX IF NOT EXISTS silver_mapping_rules_assigment_log_update_trgm ON silver_mapping_rules_assigment_log USING GIN (operation_type gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_mapping_rules_assigment_log_user_lower_idx ON silver_mapping_rules_assigment_log (lower("user"));
CREATE INDEX IF NOT EXISTS silver_mapping_rules_assigment_log_user_trgm ON silver_mapping_rules_assigment_log USING GIN ("user" gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_mapping_rules_assigment_log_operation_date_brin ON silver_mapping_rules_assigment_log USING BRIN (operation_date);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_mapping_rule_id_idx ON silver_mapping_taxonomies (mapping_rule_id);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_master_node_id_idx ON silver_mapping_taxonomies (master_node_id);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_child_node_id_idx ON silver_mapping_taxonomies (child_node_id);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_status_lower_idx ON silver_mapping_taxonomies (lower(status));
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_status_trgm ON silver_mapping_taxonomies USING GIN (status gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_user_lower_idx ON silver_mapping_taxonomies (lower("user"));
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_user_trgm ON silver_mapping_taxonomies USING GIN ("user" gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_created_at_brin ON silver_mapping_taxonomies USING BRIN (created_at);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_last_updated_at_brin ON silver_mapping_taxonomies USING BRIN (last_updated_at);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_master_child_idx ON silver_mapping_taxonomies (master_node_id, child_node_id);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_rule_idx ON silver_mapping_taxonomies (mapping_rule_id);
CREATE INDEX IF NOT EXISTS gold_mapping_taxonomies_master_node_id_idx ON gold_mapping_taxonomies (master_node_id);
CREATE INDEX IF NOT EXISTS gold_mapping_taxonomies_child_node_id_idx ON gold_mapping_taxonomies (child_node_id);
CREATE INDEX IF NOT EXISTS gold_mapping_taxonomies_created_at_brin ON gold_mapping_taxonomies USING BRIN (created_at);
CREATE INDEX IF NOT EXISTS gold_mapping_taxonomies_last_updated_at_brin ON gold_mapping_taxonomies USING BRIN (last_updated_at);
CREATE INDEX IF NOT EXISTS gold_mapping_taxonomies_master_child_idx ON gold_mapping_taxonomies (master_node_id, child_node_id);
CREATE INDEX IF NOT EXISTS gold_mapping_taxonomies_log_old_row_gin ON gold_mapping_taxonomies_log USING GIN (old_row jsonb_path_ops);
CREATE INDEX IF NOT EXISTS gold_mapping_taxonomies_log_new_row_gin ON gold_mapping_taxonomies_log USING GIN (new_row jsonb_path_ops);
CREATE INDEX IF NOT EXISTS gold_mapping_taxonomies_log_update_lower_idx ON gold_mapping_taxonomies_log (lower(operation_type));
CREATE INDEX IF NOT EXISTS gold_mapping_taxonomies_log_update_trgm ON gold_mapping_taxonomies_log USING GIN (operation_type gin_trgm_ops);
CREATE INDEX IF NOT EXISTS gold_mapping_taxonomies_log_user_lower_idx ON gold_mapping_taxonomies_log (lower("user"));
CREATE INDEX IF NOT EXISTS gold_mapping_taxonomies_log_user_trgm ON gold_mapping_taxonomies_log USING GIN ("user" gin_trgm_ops);
CREATE INDEX IF NOT EXISTS gold_mapping_taxonomies_log_operation_date_brin ON gold_mapping_taxonomies_log USING BRIN (operation_date);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_attributes_attribute_type_id_idx ON silver_taxonomies_nodes_attributes (attribute_type_id);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_attributes_node_id_idx ON silver_taxonomies_nodes_attributes (node_id);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_attributes_load_id_idx ON silver_taxonomies_nodes_attributes (load_id);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_attributes_row_id_idx ON silver_taxonomies_nodes_attributes (row_id);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_attributes_value_lower_idx ON silver_taxonomies_nodes_attributes (lower(value));
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_attributes_value_trgm ON silver_taxonomies_nodes_attributes USING GIN (value gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_attributes_created_at_brin ON silver_taxonomies_nodes_attributes USING BRIN (created_at);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_attributes_last_updated_at_brin ON silver_taxonomies_nodes_attributes USING BRIN (last_updated_at);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_attributes_node_attr_idx ON silver_taxonomies_nodes_attributes (node_id, attribute_type_id, value);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_attributes_log_old_row_gin ON silver_taxonomies_nodes_attributes_log USING GIN (old_row jsonb_path_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_attributes_log_new_row_gin ON silver_taxonomies_nodes_attributes_log USING GIN (new_row jsonb_path_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_attributes_log_update_lower_idx ON silver_taxonomies_nodes_attributes_log (lower(operation_type));
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_attributes_log_update_trgm ON silver_taxonomies_nodes_attributes_log USING GIN (operation_type gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_attributes_log_user_lower_idx ON silver_taxonomies_nodes_attributes_log (lower("user"));
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_attributes_log_user_trgm ON silver_taxonomies_nodes_attributes_log USING GIN ("user" gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_nodes_attributes_log_operation_date_brin ON silver_taxonomies_nodes_attributes_log USING BRIN (operation_date);
CREATE INDEX IF NOT EXISTS silver_taxonomies_attribute_types_attribute_type_id_idx ON silver_taxonomies_attribute_types (attribute_type_id);
CREATE INDEX IF NOT EXISTS silver_taxonomies_attribute_types_name_lower_idx ON silver_taxonomies_attribute_types (lower(name));
CREATE INDEX IF NOT EXISTS silver_taxonomies_attribute_types_name_trgm ON silver_taxonomies_attribute_types USING GIN (name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_attribute_types_created_at_brin ON silver_taxonomies_attribute_types USING BRIN (created_at);
CREATE INDEX IF NOT EXISTS silver_taxonomies_attribute_types_last_updated_at_brin ON silver_taxonomies_attribute_types USING BRIN (last_updated_at);
CREATE INDEX IF NOT EXISTS silver_taxonomies_attribute_types_log_old_row_gin ON silver_taxonomies_attribute_types_log USING GIN (old_row jsonb_path_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_attribute_types_log_new_row_gin ON silver_taxonomies_attribute_types_log USING GIN (new_row jsonb_path_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_attribute_types_log_update_lower_idx ON silver_taxonomies_attribute_types_log (lower(operation_type));
CREATE INDEX IF NOT EXISTS silver_taxonomies_attribute_types_log_update_trgm ON silver_taxonomies_attribute_types_log USING GIN (operation_type gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_attribute_types_log_user_lower_idx ON silver_taxonomies_attribute_types_log (lower("user"));
CREATE INDEX IF NOT EXISTS silver_taxonomies_attribute_types_log_user_trgm ON silver_taxonomies_attribute_types_log USING GIN ("user" gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_attribute_types_log_operation_date_brin ON silver_taxonomies_attribute_types_log USING BRIN (operation_date);
CREATE INDEX IF NOT EXISTS silver_taxonomies_versions_taxonomy_id_idx ON silver_taxonomies_versions (taxonomy_id);
CREATE INDEX IF NOT EXISTS silver_taxonomies_versions_load_id_idx ON silver_taxonomies_versions (load_id);
CREATE INDEX IF NOT EXISTS silver_taxonomies_versions_remapping_flag_true_idx ON silver_taxonomies_versions (remapping_flag);
CREATE INDEX IF NOT EXISTS silver_taxonomies_versions_remapping_reason_lower_idx ON silver_taxonomies_versions (lower(remapping_reason));
CREATE INDEX IF NOT EXISTS silver_taxonomies_versions_remapping_reason_trgm ON silver_taxonomies_versions USING GIN (remapping_reason gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_versions_total_mappings_processed_lower_idx ON silver_taxonomies_versions (total_mappings_processed);
CREATE INDEX IF NOT EXISTS silver_taxonomies_versions_total_mappings_changed_lower_idx ON silver_taxonomies_versions (total_mappings_changed);
CREATE INDEX IF NOT EXISTS silver_taxonomies_versions_total_mappings_unchanged_lower_idx ON silver_taxonomies_versions (total_mappings_unchanged);
CREATE INDEX IF NOT EXISTS silver_taxonomies_versions_total_mappings_failed_lower_idx ON silver_taxonomies_versions (total_mappings_failed);
CREATE INDEX IF NOT EXISTS silver_taxonomies_versions_total_mappings_new_lower_idx ON silver_taxonomies_versions (total_mappings_new);
CREATE INDEX IF NOT EXISTS silver_taxonomies_versions_remapping_proces_status_lower_idx ON silver_taxonomies_versions (lower(remapping_proces_status));
CREATE INDEX IF NOT EXISTS silver_taxonomies_versions_remapping_proces_status_trgm ON silver_taxonomies_versions USING GIN (remapping_proces_status gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_versions_version_notes_lower_idx ON silver_taxonomies_versions (lower(version_notes));
CREATE INDEX IF NOT EXISTS silver_taxonomies_versions_version_notes_trgm ON silver_taxonomies_versions USING GIN (version_notes gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_versions_version_to_date_lower_idx ON silver_taxonomies_versions USING BRIN(version_to_date);
CREATE INDEX IF NOT EXISTS silver_taxonomies_versions_created_at_lower_idx ON silver_taxonomies_versions USING BRIN (created_at);
CREATE INDEX IF NOT EXISTS silver_taxonomies_versions_created_at_brin ON silver_taxonomies_versions USING BRIN (created_at);
CREATE INDEX IF NOT EXISTS silver_taxonomies_versions_last_updated_at_brin ON silver_taxonomies_versions USING BRIN (last_updated_at);
CREATE INDEX IF NOT EXISTS silver_taxonomies_versions_version_from_date_brin ON silver_taxonomies_versions USING BRIN (version_from_date);
CREATE INDEX IF NOT EXISTS silver_taxonomies_versions_log_old_row_gin ON silver_taxonomies_versions_log USING GIN (old_row jsonb_path_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_versions_log_new_row_gin ON silver_taxonomies_versions_log USING GIN (new_row jsonb_path_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_versions_log_update_lower_idx ON silver_taxonomies_versions_log (lower(operation_type));
CREATE INDEX IF NOT EXISTS silver_taxonomies_versions_log_update_trgm ON silver_taxonomies_versions_log USING GIN (operation_type gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_versions_log_user_lower_idx ON silver_taxonomies_versions_log (lower("user"));
CREATE INDEX IF NOT EXISTS silver_taxonomies_versions_log_user_trgm ON silver_taxonomies_versions_log USING GIN ("user" gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_taxonomies_versions_log_operation_date_brin ON silver_taxonomies_versions_log USING BRIN (operation_date);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_versions_mapping_id_idx ON silver_mapping_taxonomies_versions (mapping_id);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_versions_superseded_by_mapping_id_idx ON silver_mapping_taxonomies_versions (superseded_by_mapping_id);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_versions_version_to_date_lower_idx ON silver_mapping_taxonomies_versions USING BRIN(version_to_date);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_versions_superseded_by_mapping_id_lower_idx ON silver_mapping_taxonomies_versions (superseded_by_mapping_id);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_versions_created_at_brin ON silver_mapping_taxonomies_versions USING BRIN (created_at);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_versions_last_updated_at_brin ON silver_mapping_taxonomies_versions USING BRIN (last_updated_at);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_versions_version_from_date_brin ON silver_mapping_taxonomies_versions USING BRIN (version_from_date);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_versions_version_to_date_brin ON silver_mapping_taxonomies_versions USING BRIN (version_to_date);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_versions_log_old_row_gin ON silver_mapping_taxonomies_versions_log USING GIN (old_row jsonb_path_ops);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_versions_log_new_row_gin ON silver_mapping_taxonomies_versions_log USING GIN (new_row jsonb_path_ops);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_versions_log_update_lower_idx ON silver_mapping_taxonomies_versions_log (lower(operation_type));
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_versions_log_update_trgm ON silver_mapping_taxonomies_versions_log USING GIN (operation_type gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_versions_log_user_lower_idx ON silver_mapping_taxonomies_versions_log (lower("user"));
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_versions_log_user_trgm ON silver_mapping_taxonomies_versions_log USING GIN ("user" gin_trgm_ops);
CREATE INDEX IF NOT EXISTS silver_mapping_taxonomies_versions_log_operation_date_brin ON silver_mapping_taxonomies_versions_log USING BRIN (operation_date);

-- inserting special values

INSERT INTO silver_taxonomies_nodes_types (node_type_id, name, status, created_at, last_updated_at)
VALUES (-1, 'N/A', 'active', NOW(), NOW());

DO $
DECLARE r record;
BEGIN
  FOR r IN
    SELECT format('ALTER TABLE %I.%I OWNER TO lambda_user;', n.nspname, c.relname) AS cmd
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'taxonomy_schema'
      AND c.relkind IN ('r','p')
  LOOP
    EXECUTE r.cmd;
  END LOOP;

  FOR r IN
    SELECT format('ALTER VIEW %I.%I OWNER TO lambda_user;', n.nspname, c.relname) AS cmd
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'taxonomy_schema'
      AND c.relkind = 'v'
  LOOP
    EXECUTE r.cmd;
  END LOOP;

  FOR r IN
    SELECT format('ALTER MATERIALIZED VIEW %I.%I OWNER TO lambda_user;', n.nspname, c.relname) AS cmd
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'taxonomy_schema'
      AND c.relkind = 'm'
  LOOP
    EXECUTE r.cmd;
  END LOOP;

  FOR r IN
    SELECT format('ALTER FOREIGN TABLE %I.%I OWNER TO lambda_user;', n.nspname, c.relname) AS cmd
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'taxonomy_schema'
      AND c.relkind = 'f'
  LOOP
    EXECUTE r.cmd;
  END LOOP;

  FOR r IN
    SELECT format('ALTER SEQUENCE %I.%I OWNER TO lambda_user;', n.nspname, c.relname) AS cmd
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'taxonomy_schema'
      AND c.relkind = 'S'
      AND NOT EXISTS (
        SELECT 1
        FROM pg_depend d
        WHERE d.classid = 'pg_class'::regclass
          AND d.objid   = c.oid
          AND d.deptype IN ('a','i')   -- serial/identity
      )
  LOOP
    EXECUTE r.cmd;
  END LOOP;
END$;
